"use client";
import { Navbar } from "@/components/Navbar";
import "./globals.css";
import { FooterGeneral } from "@/components/FooterGeneral";
import { Provider } from "react-redux";
import { store } from "@/store/store";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <Navbar></Navbar>
          {children}
          <FooterGeneral></FooterGeneral>
        </Provider>
      </body>
    </html>
  );
}
